name: Daily Task Creation

on:
  schedule:
    - cron: '0 02 * * *'  # This is 2 AM UTC, which corresponds to 5 AM Moscow Time (UTC+3)
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Specify your Python version here

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run the script
      run: python main.py
      env:
        CLICKUP_API_KEY: ${{ secrets.CLICKUP_API_KEY }}
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
        SMTP_USER: ${{ secrets.SMTP_USER }}
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
